version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_NAME=project_ara
      - DB_SSL_MODE=disable
      - GIN_MODE=debug
    depends_on:
      - postgres
    volumes:
      - .:/app
    networks:
      - project-ara-network

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=project_ara
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - project-ara-network

volumes:
  postgres_data:

networks:
  project-ara-network:
    driver: bridge 